accounts/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from accounts.views import signup, SubscriptionListView, SubscriptionDetailView, BasketListView

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name = "login"),
    path("logout/", auth_views.LogoutView.as_view(), name = "logout"),
    path("signup/", signup, name="signup"),
    path("price/", SubscriptionListView.as_view(), name = "price"),
    path("<int:pk>/", SubscriptionDetailView.as_view(), name = "price_detail"),
    path("basket/", BasketListView.as_view(), name = "basket")
]

optimum/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic.base import RedirectView
from django.urls import include, path, reverse_lazy

urlpatterns = [
    path('admin/', admin.site.urls),
    path("recipes/", include('recipes.urls')),
    path("accounts/", include('accounts.urls')),
]

recipes/urls.py
from django.urls import path

from recipes.views import (
    RecipeListView,
    RecipeDetailView,
    ProductListView
)

from django.views.generic.base import RedirectView

urlpatterns = [
    path("list/", RecipeListView.as_view(), name="recipe_list"),
    path("<str:pk>/", RecipeDetailView.as_view(), name = "recipe_detail"),
    path("", ProductListView.as_view(), name = "home")
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class Subscription(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.IntegerField()
    tax = models.FloatField() #find API for tax from each state
    total = models.FloatField()
    member = models.ForeignKey(User, related_name="members", on_delete=models.CASCADE)

SUBSCRIPTION_CHOICES = [
        ('Best', "i am the best plan $250"),
        ('Ehhh', "Do you really care about health? $150" ),
        ('Worst', "Yea you dont care $75")
    ]
class Tsubscription(models.Model):
    slug = models.SlugField(null=True, blank=True)
    subscription = models.CharField(max_length=50, choices=SUBSCRIPTION_CHOICES)
    price = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    # owner = models.ForeignKey(User, related_name="tsub", on_delete=models.CASCADE, null = True)

    def __str__(self):
        return self.subscription

class SubPlan(models.Model):
    title=models.CharField(max_length=150)
    price = models.IntegerField()
    highlight_status=models.BooleanField(default=False, null=True)

    def __str__(self):
        return self.title

class SubPlanFeature(models.Model):
    subplan = models.ForeignKey(SubPlan, related_name="subplan" ,on_delete=models.CASCADE)
    title= models.CharField(max_length=150)

    def __str__(self):
        return self.title




# class Usersubscription(models.Model):
#     user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name="user_sub", on_delete=models.SET_NULL, null =True)
#     subscription = models.ForeignKey("Tsubscription", related_name='user_sub', on_delete=models.SET_NULL, null = True)

#     def __str__(self):
#         return self.user.username

# class Subinfo(models.Model):
#     subscription = models.ForeignKey("Usersubscription", related_name="subinfo", on_delete=models.CASCADE)
#     active = models.BooleanField(default=True)

#     def __str__(self):
#         return self.subscription.user.username



class Basket(models.Model):
    user = models.ForeignKey(User, related_name="basket", on_delete=models.CASCADE)
    recipe_item = models.ForeignKey("recipes.Recipe", on_delete=models.PROTECT)

    def __str__(self):
        return str(self.recipe_item)

calorie/models.py
from django.db import models

# Create your models here.

recipes/models.py
from django.db import models
from django.conf import settings
# Create your models here.

USER_MODEL = settings.AUTH_USER_MODEL


class Recipe(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    image = models.URLField(null=True, blank= True)
    servings = models.PositiveIntegerField(blank=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=50)
    measurement = models.ForeignKey("Measure", related_name="measurement", on_delete=models.PROTECT)
    amount = models.FloatField()
    recipe = models.ForeignKey("Recipe", related_name="ingredients", on_delete=models.CASCADE)

    def __str__(self):
        amount = str(self.amount)
        measurement = self.measurement.name
        name = self.name
        return amount + " " + measurement + " " + name

class Step(models.Model):
    recipe = models.ForeignKey("Recipe", related_name="steps", on_delete=models.CASCADE)
    directions = models.CharField(max_length=300)
    order = models.PositiveSmallIntegerField()

    def __str__(self):
        return f'Step {self.order}: {self.directions} - {self.recipe.name} recipe'


class Measure(models.Model):
    name = models.CharField(max_length=30, unique = True)
    abbreviation = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name

accounts/views.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth import login
from accounts.models import Tsubscription, Basket, SubPlan, SubPlanFeature
from django.forms import BaseModelFormSet
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            # firstname = request.POST.get("firstname")
            # lastname = request.POST.get("lastname")
            # age = request.POST.get("age")
            # gender = request.POST.get('gender')
            # address = request.POST.get("address")
            user = User.objects.create_user(
                username=username, password=password
            )
            # , firstname = firstname, lastname = lastname, age = age, gender = gender, address = address
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {"form":form}
    return render(request, "registration/signup.html", context)



class SubscriptionListView(ListView):
    model = SubPlan
    template_name = "accounts/price.html"

    # def get_user_tsubscription(self):
    #     user_tsubscription_qs=Usersubscription.objects.filter(user=self.request.user)
    #     if user_sub_qs.exists():
    #         return user_sub_qs.first()
    #     return None

    # def get_context_data(self, *args,**kwargs):
    #     context = super().get_context_data(**kwargs)
    #     current_sub = self.get_subscription(self.request)
    #     context["current_sub"] = str(current_sub.tsubscription)
    #     return context

class SubscriptionCreate(CreateView):
    model = Tsubscription
    template_name = "accounts/create.html"
    fields = ["subscription"]

    def form_invalid(self, form):
        plan = form.save(commit=False)
        plan.owner=self.request.user
        plan.save()
        form.save_m2m()
        return redirect("home", pk=plan.id)
class SubscriptionDetailView(DetailView):
    model = SubPlan
    template_name = "accounts/detail.html"

class SubplanCheckout(ListView):
    model = SubPlan

class BasketListView(LoginRequiredMixin, ListView):
    model = Basket
    template_name = "basket/list.html"

    def get_queryset(self):
        return Basket.objects.filter(user=self.request.user)

calorie/views.py
from django.shortcuts import render

# Create your views here.

recipes/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from recipes.models import Recipe
from django.views.generic.detail import DetailView
from django.core.paginator import Paginator

# Create your views here.
class RecipeListView(ListView):
    model = Recipe
    template_name = "recipes/list.html"
    paginate_by = 2

class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipes/detail.html"

class ProductListView(ListView):
    model = Recipe
    template_name = "home.html"

accounts/templates/accounts/checkout.html
<<<<<<< HEAD
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="col my-4">
        <h2> Step 1 - My Awesome Cart Express Checkout - Review Your Cart items </h2>
        <div id='items'>
            <ul class="list-group">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Cras justo odio
                    <span class="badge badge-primary badge-pill">14</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Dapibus ac facilisis in
                    <span class="badge badge-primary badge-pill">2</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Morbi leo risus
                    <span class="badge badge-primary badge-pill">1</span>
                </li>
            </ul>
        </div>
    </div>
    <div class="col my-4">
        <h2> Step 2 - Enter Address & Other Details</h2>
        <form>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="name">Name</label>
                    <input type="name" class="form-control" id="name" placeholder="Name">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputEmail4">Email</label>
                    <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
                </div>
            </div>
            <div class="form-group">
                <label for="inputAddress">Address</label>
                <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
            </div>
            <div class="form-group">
                <label for="inputAddress2">Address Line 2</label>
                <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputCity">City</label>
                    <input type="text" class="form-control" id="inputCity">
                </div>
                <div class="form-group col-md-4">
                    <label for="inputState">State</label>
                    <input type="text" class="form-control" id="inputAddress" placeholder="Enter State">
                    </select>
                </div>
                <div class="form-group col-md-2">
                    <label for="inputZip">Zip</label>
                    <input type="text" class="form-control" id="inputZip">
                </div>
            </div>
            <div class="form-group">
                <label for="inputZip">Phone Number</label>
                <input type="tel" class="form-control" id="inputPhone">
            </div>
            <button type="submit" class="btn btn-primary">Place Order</button>
        </form>
    </div>
</div>
{% endblock content %}
=======
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="col my-4">
        <h2> Step 1 - My Awesome Cart Express Checkout - Review Your Cart items </h2>
        <div id='items'>
            <ul class="list-group">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Cras justo odio
                    <span class="badge badge-primary badge-pill">14</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Dapibus ac facilisis in
                    <span class="badge badge-primary badge-pill">2</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Morbi leo risus
                    <span class="badge badge-primary badge-pill">1</span>
                </li>
            </ul>
        </div>
    </div>
    <div class="col my-4">
        <h2> Step 2 - Enter Address & Other Details</h2>
        <form>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="name">Name</label>
                    <input type="name" class="form-control" id="name" placeholder="Name">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputEmail4">Email</label>
                    <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
                </div>
            </div>
            <div class="form-group">
                <label for="inputAddress">Address</label>
                <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
            </div>
            <div class="form-group">
                <label for="inputAddress2">Address Line 2</label>
                <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputCity">City</label>
                    <input type="text" class="form-control" id="inputCity">
                </div>
                <div class="form-group col-md-4">
                    <label for="inputState">State</label>
                    <input type="text" class="form-control" id="inputAddress" placeholder="Enter State">
                    </select>
                </div>
                <div class="form-group col-md-2">
                    <label for="inputZip">Zip</label>
                    <input type="text" class="form-control" id="inputZip">
                </div>
            </div>
            <div class="form-group">
                <label for="inputZip">Phone Number</label>
                <input type="tel" class="form-control" id="inputPhone">
            </div>
            <button type="submit" class="btn btn-primary">Place Order</button>
        </form>
    </div>
</div>
{% endblock content %}
>>>>>>> 28538822537e17c6b29dc5759d80c92b4d0e425f

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
        <h1>{{subplan.title}}</h1>
        {% for sub in subplan.subplan.all %}
        <p>{{sub.title}}</p>
        {% endfor %}
    </div>
    <div>
        <a href="{% url 'checkout' %}"><button>
            Checkout
        </button></a>
    </div>
</main>
{% endblock content %}

accounts/templates/accounts/price.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
<<<<<<< HEAD
    <div>
        <h1>Subscription Plan</h1>
        <table>
            <thead>
                <th>Subscription</th>
                <th>Prices</th>
            </thead>
            <tbody>
                {% for sub in subplan_list %}
                <tr>
                    <td>{{sub.title}}</a></td>
                    <td>
                        {{sub.price}}
                    </td>
                    <td>
                        <form method="POST">
                            {% csrf_token %}
                            <input
                            type="hidden"
                            name="sub_id"
                            value="{{sub.id}}"
                            />
                            <a href="{% url 'price_detail' sub.pk %}"><button type="button">Get started</button></a>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
=======
<div class="pricing-container">
    <div class="pricing-header">
        <h1 class="pricing-title">Our Subscriptions</h1>
            <div class="toggle">
                <label for="">Annually</label>
                <div class="toggle-btn">
                    <input type="checkbox" id="checkbox" class="checkbox">
                    <label for="checkbox" class="sub" id="suv">
                        <div class="circle"></div>
                    </label>
                </div>
                <label for="">Monthly</label>
        </div>
>>>>>>> 2e0333f6476abccce8752b5e617dd56be749cdcc
    </div>
    {% comment %} cards {% endcomment %}

    <div class="cards">
        <div class="card shadow">
            <ul class="pricing-list">
                <li class="pack pricing-li">Basic</li>
                <li id="basic" class="price bottom-bar pricing-li">
                    &dollar; 154.99
                </li>
                <li class="bottom-bar pricing-li">3 meals for 2 people per week</li>
                <li class="bottom-bar pricing-li">6 total servings</li>
                <li class="bottom-bar pricing-li"> 1 Free Meal </li>
                <li class="bottom-bar pricing-li">Price Per Serving &dollar; 25.83</li>
                <li class="pricing-li">
                    <button class="pricing-btn">Select This Plan</button>
                </li>
            </ul>
        </div>
        <div class="card active">
            <ul class="pricing-list">
                <li class="pack pricing-li">Recommended</li>
                <li id="basic" class="price bottom-bar pricing-li price-active">
                    &dollar; 254.99
                </li>
                <li class="bottom-bar pricing-li">6 meals for 2 people per week</li>
                <li class="bottom-bar pricing-li">12 total servings</li>
                <li class="bottom-bar pricing-li"> 3 Free Meals </li>
                <li class="bottom-bar pricing-li">Price Per Serving &dollar; 21.25 </li>
                <li class="pricing-li">
                    <button class="pricing-btn active-btn">Select This Plan</button>
                </li>
            </ul>
        </div>
        <div class="card shadow">
            <ul class="pricing-list">
                <li class="pack pricing-li">Premium</li>
                <li id="basic" class="price bottom-bar pricing-li">
                    &dollar; 354.99
                </li>
                <li class="bottom-bar pricing-li">10 meals for 2 people per week</li>
                <li class="bottom-bar pricing-li">20 total servings</li>
                <li class="bottom-bar pricing-li"> 5 Free Meals </li>
                <li class="bottom-bar pricing-li">Price Per Serving &dollar; 17.75</li>
                <li class="pricing-li">
                    <button class="pricing-btn">Select This Plan</button>
                </li>
            </ul>
        </div>
    </div>
</div>
</main>
{% endblock content %}


{% comment %} <ul>
    {% for sub in tsubscription_list %}
    <li>
        <a href="{% url 'price_detail' sub.pk %}">
        </a>
    </li>
    {% endfor %}
</ul> {% endcomment %}

accounts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link rel="stylesheet" href="{% static 'script.js' %}">

    <title>Optimeal</title>
</head>
<body>
    <header class="header sticky" >
        <a href="{% url 'home' %}">
            <img class="logo" src="{% static 'images/homepage_img/logo.png' %}" alt="">
        </a>
        <nav class="main-nav">
            <ul class="main-nav-list">
                <li>
                    <a class="main-nav-link" href="#">How it Works</a>
                </li>
                <li>
                    <a class="main-nav-link" href="{% url 'recipe_list' %}">Our Recipes</a>
                </li>
                <li>
                    <a class="main-nav-link" href="#">Testimonials</a>
                </li>
                <li>
                    <a class="main-nav-link" href="{% url 'price' %}">Pricing</a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a class="main-nav-link" href="{% url 'basket' %}">Basket ({{ Basket.recipe_item.all | length }})</a>
                </li>
                <li>
                    <a class="main-nav-link" href="{% url 'logout' %}">Log out</a>
                </li>
                {% else %}
                <li>
                    <a class="main-nav-link" href="{% url 'login' %}">Log in</a>
                </li>
                <li>
                    <a class="main-nav-link nav-cta" href="{% url 'signup' %}">Try for Free!</a>
                </li>

                {% endif %}
            </ul>
        </nav>
        {% block pagination %}
        {% endblock pagination %}
    </header>
    {% block content %}
    {% endblock content %}
</body>
</html>

accounts/templates/basket/list.html
<<<<<<< HEAD
{% extends 'base.html' %}
{% block content %}
<main>
    <h1>You Recipe Basket</h1>
    <div>
        <ul>
            {% for item in basket_list %}
            <li>{{item.recipe_item}}</li>
            {% endfor %}
        </ul>
    </div>
</main>
{% endblock content %}
=======
{% extends 'base.html' %}
{% block content %}
<main>
    <h1>You Recipe Basket</h1>
    <div>
        <ul>
            {% for item in basket_list %}
            <li>{{item.recipe_item}}</li>
            {% endfor %}
        </ul>
    </div>
</main>
{% endblock content %}
>>>>>>> 28538822537e17c6b29dc5759d80c92b4d0e425f

recipes/templates/recipes/detail.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
    <h1>{{recipe.name}}</h1>
    <div>
        <img src="{{recipe.image}}">
    </div>
    <div>
        <p>{{recipe.description}}</p>
        <h5>{{recipe.servings}}</h5>
    </div>
    <div>
        <p>{{recipe.ingredients.amount}} {{recipe.ingredients.measurement}} {{recipe.ingredients.name}}</p>
    </div>
    </div>
</main>
{% endblock content %}

recipes/templates/recipes/list.html
{% extends 'base.html' %}
{% block pagination %}
<div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
{% endblock pagination %}
{% block content %}
<main>
    {% for recipe in recipe_list %}
    <li>
      <a href="{% url 'recipe_detail' recipe.id %}">{{recipe.name}}</a>
    </li>
    {% comment %} {{recipe.image}} {% endcomment %}
    {% endfor %}
</main>
{% endblock content %}